apiVersion: v1
data:
  google-service-account: {{ .Values.google_service_account_json | toPrettyJson | b64enc | quote }}
kind: Secret
metadata:
  name: {{ include "mongodb-backup-aws.fullname" . }}
  namespace: default
type: Opaque