apiVersion: v1
data:
  google-service-account: {{ .Values.google_service_account_json | toPrettyJson | b64enc | quote }}
kind: Secret
metadata:
  name: gcloud-credental
  namespace: default
type: Opaque
