version: '3'

services:
  mongo_backup:
    build:
      context: .
    container_name: mongodb_backup_migrate
    volumes:
      - ./google-service-account.json:/google-service-account.json:ro
      - ./backup:/backup
    environment:
      MONGODB_HOST: host
      MONGODB_PORT: port
      MONGODB_URI: "mongodb://backup:VfZYPXPXjL76DqYBB@main-mongodb-headless/trainer_bot?replicaSet=rs0"
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
      GOOGLE_STORAGE: mongo-backup-ncet
      MAX_BACKUPS: 30
      CRON_SCHEDULE: "*/3 * * * *"
      GCLOUD_KEY: 
      RUN_AS_DAEMON: 'true'
      INIT_BACKUP: 'false'
      INIT_RESTORE: 'false'